package de.taz.app.android.api.models

enum class SubscriptionStatus {
    alreadyLinked,
    elapsed,
    ibanNoIban,
    ibanInvalidChecksum,
    ibanNoSepaCountry,
    invalidAccountHolder,
    invalidCity,
    invalidConnection,
    invalidCountry,
    invalidFirstName,
    invalidMail,
    invalidPostcode,
    invalidSurname,
    invalidStreet,
    nameTooLong,
    noFirstName,
    noPollEntry,
    noSurname,
    priceNotValid,
    subscriptionIdNotValid,
    tazIdNotValid,
    tooManyPollTries,
    valid,
    waitForMail,
    waitForProc,
    UNKNOWN_RESPONSE
}